name: Build
on: 
  pull_request:
      branches:
        - main

jobs:
  build-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
