name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
