name: Publish tokens
on: 
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  build-deploy:
    name: Publish package
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Publish
        uses: JS-DevTools/npm-publish@c196e53609e852c243616a87994e8961a9903ba4
        with:
          token: ${{ secrets.NPM_TOKEN }}
